### ISSUE TITLE
Grade calculation over multiple attainments

### ISSUE THREAD

**Issue by PasiSa** [aalto-grades/base-repository#224]
When calculating grades, teacher should have a way to include assignments from earlier course instances, and the system should be able to show and propose the possible assignments to use in calculation, considering their expiry date. 

- [x] #250
- [ ] The UI should be able to show the different grade sources somehow intuitively, also in results view: for example, teacher should easily see if student has participated in two exams
- [x] If a student has multiple grades for the same attainment, the better grade is accounted for in the grade calculation
- [x] It should be possible to choose between multiple formulas for grade calculation. For now, this can be a static hard-coded set
- [ ] #403
