### ISSUE TITLE
Upload grades dialog improvements

### ISSUE THREAD

**Issue by bntti** [aalto-grades/base-repository#604]
- [ ] Update expiration date when changing submission date
- [ ] Don't gray out confirm button, instead just open up the next dialog when pressing it
- [ ] Start date picker calendar from monday
