### ISSUE TITLE
Graph view improvements

### ISSUE THREAD

**Issue by bntti** [aalto-grades/base-repository#605]
- [x] Make it clear that attainment test values are actually test values
  - Make them visually somehow separate from node settings inputs
- [x] Add rounding node
- [x] Make 'coursefail' status more clear
  - Make entire view red not just the one node?
- [x] Add templates for graph
- [x] Remove word 'node' from drag and drop -nodes
- [x] Use drag pointer when hovering over drag and drop -nodes
- [x] Don't allow navigating away when unsaved changes
- [x] Make unsaved changes more clear
- [x] Show some popup when saving successfully (only show after backend response)
- [x] Use custom unsaved changes prompt and not the browser native one
- [x] Add cancel and done buttons to the select attainments dialog
- [x] Make select attainments button and other buttons less hidden
- [x] Make node input and output values more clear
- [x] Attainment node set minimum required points
  - requires "Make it clear that attainment test values are actually test values"
- [x] Allow to zoom more out
- [x] Add options to requireMiminumPoints node to fail course / output zero on fail
- [x] Add percentage option to AverageNode
