### ISSUE TITLE
Fix tests and create new ones

### ISSUE THREAD

**Issue by bntti** [aalto-grades/base-repository#612]
- [x] Fix existing frontend tests
- [ ] Create new relevant frontend tests
- [x] Fix existing backend tests
- [x] #665

**Comment by no-comma** [comment]
Creating new frontend tests may not be necessary, and the existing ones could potentially be removed in favor of end-to-end tests.

Is there anything that should be tested specifically with frontend tests, or would all of the necessary functionality already get tested in end-to-end tests?
